# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64ummy.proto\"2\n\nParameters\x12\x0f\n\x07tensors\x18\x01 \x03(\x0c\x12\x13\n\x0btensor_type\x18\x02 \x01(\t\"\x86\x01\n\x06\x46itIns\x12\x1f\n\nparameters\x18\x01 \x01(\x0b\x32\x0b.Parameters\x12#\n\x06\x63onfig\x18\x02 \x03(\x0b\x32\x13.FitIns.ConfigEntry\x1a\x36\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Scalar:\x02\x38\x01\"\x90\x01\n\x0b\x45valuateIns\x12\x1f\n\nparameters\x18\x01 \x01(\x0b\x32\x0b.Parameters\x12(\n\x06\x63onfig\x18\x02 \x03(\x0b\x32\x18.EvaluateIns.ConfigEntry\x1a\x36\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Scalar:\x02\x38\x01\"\x1b\n\tFinishIns\x12\x0e\n\x06\x66inish\x18\x01 \x01(\t\"\x1b\n\tFinishRes\x12\x0e\n\x06\x66inish\x18\x01 \x01(\t\"\x9f\x01\n\x06\x46itRes\x12\x1f\n\nparameters\x18\x01 \x01(\x0b\x32\x0b.Parameters\x12\x14\n\x0cnum_examples\x18\x02 \x01(\x03\x12%\n\x07metrics\x18\x03 \x03(\x0b\x32\x14.FitRes.MetricsEntry\x1a\x37\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Scalar:\x02\x38\x01\"\x96\x01\n\x0b\x45valuateRes\x12\x14\n\x0cnum_examples\x18\x01 \x01(\x03\x12\x0c\n\x04loss\x18\x02 \x01(\x02\x12*\n\x07metrics\x18\x03 \x03(\x0b\x32\x19.EvaluateRes.MetricsEntry\x1a\x37\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.Scalar:\x02\x38\x01\"i\n\x06Scalar\x12\x10\n\x06\x64ouble\x18\x01 \x01(\x01H\x00\x12\x10\n\x06sint64\x18\x08 \x01(\x12H\x00\x12\x0e\n\x04\x62ool\x18\r \x01(\x08H\x00\x12\x10\n\x06string\x18\x0e \x01(\tH\x00\x12\x0f\n\x05\x62ytes\x18\x0f \x01(\x0cH\x00\x42\x08\n\x06scalar2}\n\x0c\x44ummyService\x12\x1f\n\tTestTrain\x12\x07.FitIns\x1a\x07.FitRes\"\x00\x12(\n\x08TestEval\x12\x0c.EvaluateIns\x1a\x0c.EvaluateRes\"\x00\x12\"\n\x06\x46inish\x12\n.FinishIns\x1a\n.FinishRes\"\x00\x62\x06proto3')



_PARAMETERS = DESCRIPTOR.message_types_by_name['Parameters']
_FITINS = DESCRIPTOR.message_types_by_name['FitIns']
_FITINS_CONFIGENTRY = _FITINS.nested_types_by_name['ConfigEntry']
_EVALUATEINS = DESCRIPTOR.message_types_by_name['EvaluateIns']
_EVALUATEINS_CONFIGENTRY = _EVALUATEINS.nested_types_by_name['ConfigEntry']
_FINISHINS = DESCRIPTOR.message_types_by_name['FinishIns']
_FINISHRES = DESCRIPTOR.message_types_by_name['FinishRes']
_FITRES = DESCRIPTOR.message_types_by_name['FitRes']
_FITRES_METRICSENTRY = _FITRES.nested_types_by_name['MetricsEntry']
_EVALUATERES = DESCRIPTOR.message_types_by_name['EvaluateRes']
_EVALUATERES_METRICSENTRY = _EVALUATERES.nested_types_by_name['MetricsEntry']
_SCALAR = DESCRIPTOR.message_types_by_name['Scalar']
Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERS,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:Parameters)
  })
_sym_db.RegisterMessage(Parameters)

FitIns = _reflection.GeneratedProtocolMessageType('FitIns', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _FITINS_CONFIGENTRY,
    '__module__' : 'dummy_pb2'
    # @@protoc_insertion_point(class_scope:FitIns.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _FITINS,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:FitIns)
  })
_sym_db.RegisterMessage(FitIns)
_sym_db.RegisterMessage(FitIns.ConfigEntry)

EvaluateIns = _reflection.GeneratedProtocolMessageType('EvaluateIns', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVALUATEINS_CONFIGENTRY,
    '__module__' : 'dummy_pb2'
    # @@protoc_insertion_point(class_scope:EvaluateIns.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _EVALUATEINS,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:EvaluateIns)
  })
_sym_db.RegisterMessage(EvaluateIns)
_sym_db.RegisterMessage(EvaluateIns.ConfigEntry)

FinishIns = _reflection.GeneratedProtocolMessageType('FinishIns', (_message.Message,), {
  'DESCRIPTOR' : _FINISHINS,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:FinishIns)
  })
_sym_db.RegisterMessage(FinishIns)

FinishRes = _reflection.GeneratedProtocolMessageType('FinishRes', (_message.Message,), {
  'DESCRIPTOR' : _FINISHRES,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:FinishRes)
  })
_sym_db.RegisterMessage(FinishRes)

FitRes = _reflection.GeneratedProtocolMessageType('FitRes', (_message.Message,), {

  'MetricsEntry' : _reflection.GeneratedProtocolMessageType('MetricsEntry', (_message.Message,), {
    'DESCRIPTOR' : _FITRES_METRICSENTRY,
    '__module__' : 'dummy_pb2'
    # @@protoc_insertion_point(class_scope:FitRes.MetricsEntry)
    })
  ,
  'DESCRIPTOR' : _FITRES,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:FitRes)
  })
_sym_db.RegisterMessage(FitRes)
_sym_db.RegisterMessage(FitRes.MetricsEntry)

EvaluateRes = _reflection.GeneratedProtocolMessageType('EvaluateRes', (_message.Message,), {

  'MetricsEntry' : _reflection.GeneratedProtocolMessageType('MetricsEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVALUATERES_METRICSENTRY,
    '__module__' : 'dummy_pb2'
    # @@protoc_insertion_point(class_scope:EvaluateRes.MetricsEntry)
    })
  ,
  'DESCRIPTOR' : _EVALUATERES,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:EvaluateRes)
  })
_sym_db.RegisterMessage(EvaluateRes)
_sym_db.RegisterMessage(EvaluateRes.MetricsEntry)

Scalar = _reflection.GeneratedProtocolMessageType('Scalar', (_message.Message,), {
  'DESCRIPTOR' : _SCALAR,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:Scalar)
  })
_sym_db.RegisterMessage(Scalar)

_DUMMYSERVICE = DESCRIPTOR.services_by_name['DummyService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FITINS_CONFIGENTRY._options = None
  _FITINS_CONFIGENTRY._serialized_options = b'8\001'
  _EVALUATEINS_CONFIGENTRY._options = None
  _EVALUATEINS_CONFIGENTRY._serialized_options = b'8\001'
  _FITRES_METRICSENTRY._options = None
  _FITRES_METRICSENTRY._serialized_options = b'8\001'
  _EVALUATERES_METRICSENTRY._options = None
  _EVALUATERES_METRICSENTRY._serialized_options = b'8\001'
  _PARAMETERS._serialized_start=15
  _PARAMETERS._serialized_end=65
  _FITINS._serialized_start=68
  _FITINS._serialized_end=202
  _FITINS_CONFIGENTRY._serialized_start=148
  _FITINS_CONFIGENTRY._serialized_end=202
  _EVALUATEINS._serialized_start=205
  _EVALUATEINS._serialized_end=349
  _EVALUATEINS_CONFIGENTRY._serialized_start=148
  _EVALUATEINS_CONFIGENTRY._serialized_end=202
  _FINISHINS._serialized_start=351
  _FINISHINS._serialized_end=378
  _FINISHRES._serialized_start=380
  _FINISHRES._serialized_end=407
  _FITRES._serialized_start=410
  _FITRES._serialized_end=569
  _FITRES_METRICSENTRY._serialized_start=514
  _FITRES_METRICSENTRY._serialized_end=569
  _EVALUATERES._serialized_start=572
  _EVALUATERES._serialized_end=722
  _EVALUATERES_METRICSENTRY._serialized_start=514
  _EVALUATERES_METRICSENTRY._serialized_end=569
  _SCALAR._serialized_start=724
  _SCALAR._serialized_end=829
  _DUMMYSERVICE._serialized_start=831
  _DUMMYSERVICE._serialized_end=956
# @@protoc_insertion_point(module_scope)
